// Build-time favicon generator. Single source of truth: assets/brand/logo-1024.png.
// Produces packages/gw-worker/src/favicon.generated.ts (a 32x32 PNG embedded as
// base64) so the Worker can serve it without filesystem access at runtime and
// without shipping the ~1 MB full-resolution logo on every favicon hit.
// Never edit the generated file by hand; re-run this when the logo changes.
// Runs on plain Node (uses the built-in image decode via sharp if present,
// else falls back to the pre-generated committed favicon — see package script).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const png = await sharp(join(root, "assets/brand/logo-1024.png"))
  .resize(32, 32, { fit: "cover" })
  .png({ compressionLevel: 9 })
  .toBuffer();

const gen =
  "// GENERATED by scripts/generate-favicon.mjs — do not edit.\n" +
  "// Source of truth: assets/brand/logo-1024.png.\n" +
  `export const FAVICON_PNG_B64 = ${JSON.stringify(png.toString("base64"))};\n`;

writeFileSync(join(root, "packages/gw-worker/src/favicon.generated.ts"), gen);
console.log(`favicon.generated.ts written (${png.length} bytes, 32x32 png)`);
