// Pure, dependency-free core of the AccountExport plugin: everything here
// compiles WITHOUT GWCA, Win32 or imgui, so it is unit-tested on the fast
// Linux CI (tests/core_tests.cpp) while the real plugin build on Windows
// keeps proving MSVC /W4 /WX integration. Keep this header pure: no game
// types — templates take any array-like (the real GW::Array satisfies it).
#pragma once

#include <cstdint>
#include <cstdio>
#include <iterator>
#include <string>

namespace account_export {

// KEEP IN SYNC with packages/gw-data/data/heroes.json (generated by
// import:heroes from the GWCA HeroID enum): if Reforged ever adds a hero,
// both this table and the overlay must gain the entry, or exports will
// label the new hero "Unknown".
// Indexed by GW::Constants::HeroID (Constants.h). Names are the canonical
// English hero names as used by gw1-mcp / the wiki.
constexpr const char* kHeroNames[] = {
    "None", "Norgu", "Goren", "Tahlkora", "Master of Whispers",
    "Acolyte Jin", "Koss", "Dunkoro", "Acolyte Sousuke", "Melonni",
    "Zhed Shadowhoof", "General Morgahn", "Magrid the Sly", "Zenmai",
    "Olias", "Razah", "M.O.X.", "Keiran Thackeray", "Jora",
    "Pyre Fierceshot", "Anton", "Livia", "Hayda", "Kahmu",
    "Gwen", "Xandra", "Vekk", "Ogden Stonehealer", "Merc1", "Merc2",
    "Merc3", "Merc4", "Merc5", "Merc6", "Merc7", "Merc8",
};

inline const char* HeroName(const uint32_t hero_id)
{
    if (hero_id < std::size(kHeroNames)) {
        return kHeroNames[hero_id];
    }
    return "Unknown";
}

inline void JsonEscapeInto(std::string& out, const std::string& value)
{
    for (const char c : value) {
        switch (c) {
            case '"': out += "\\\""; break;
            case '\\': out += "\\\\"; break;
            case '\n': out += "\\n"; break;
            case '\r': out += "\\r"; break;
            case '\t': out += "\\t"; break;
            default:
                if (static_cast<unsigned char>(c) < 0x20) {
                    char buffer[8];
                    snprintf(buffer, sizeof(buffer), "\\u%04x", c);
                    out += buffer;
                }
                else {
                    out += c;
                }
        }
    }
}

// Append the set bit indices of a skill-unlock bitfield as a JSON array of
// skill ids (bit index == template skill id). ArrayLike only needs valid(),
// size() and operator[]; the real GW::Array<uint32_t> satisfies it, and the
// tests use a plain struct.
template <typename ArrayLike>
void AppendSkillBitfield(std::string& out, const ArrayLike& bitfield)
{
    out += '[';
    bool first = true;
    if (bitfield.valid()) {
        for (uint32_t word_index = 0; word_index < bitfield.size(); word_index++) {
            const uint32_t word = bitfield[word_index];
            if (!word) {
                continue;
            }
            for (uint32_t bit = 0; bit < 32; bit++) {
                if (word & (1u << bit)) {
                    if (!first) {
                        out += ',';
                    }
                    out += std::to_string(word_index * 32 + bit);
                    first = false;
                }
            }
        }
    }
    out += ']';
}

} // namespace account_export
